@startuml
' ===== Parsing command =====
title Parsing command

skinparam shadowing false
skinparam defaultFontName Arial
skinparam rectangle {
  RoundCorner 12
  FontSize 14
}

rectangle "UI" as UI #E3F2FD
rectangle "Logic/Parser" as P #E8F5E9

UI -right-> P : measure waist/70 hips/98 chest/90 thigh/55 arm/30
P -left-> UI  : AddMeasurementCommand(70,98,90,55,30)

@enduml
