@startuml ValidationAppendWeight
title Validation & Append

skinparam component {
  BorderColor black
  BackgroundColor white
  FontSize 12
}

' Define the object instances
object "EntryList (before)" as EL_B
object "EntryList (after)" as EL_A {
}
object "WeightEntry" as ME {
  [WEIGHT] 60.00kg
}

' 1. Show the action (Append)
EL_B -right-> EL_A : append new WeightEntry

' 2. Show the containment/link relationship
'    The EntryList (after) contains the new WeightEntry
EL_A o-- ME : contains

@enduml